### ISSUE TITLE
Hur långt har du kommit på projektet ?

### ISSUE THREAD

**Issue by Uppsa1a** [DrkTheDon/Swish-app#2]
Tja jag undrar bara hur det går med appen och jag undra även om du kunde berätta vart man kan få tag på appen när den är färdig. Skulle verkligen uppskatta om du publicera en färdigt apk i "releases" på Swish-drk projektet (För Android)

**Comment by bluebudder** [comment]
Jag undrar med

**Comment by DrkTheDon** [comment]
Sorry men har och tänker inte arbeta med projektet längre. Tanken var att jag skulle arbeta med vänner men de blev inte av, sorry.

**Comment by Tjacktomten666** [comment]
Jag undrar med hur det går med publicera appen. Eller någon som har förslag vad man kan ladda ner den från annan hemsida
